name: Deploy NestJS Backend to AWS ECS

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yaml'

permissions:
  id-token: write
  contents: read

env:
  NODE_VERSION: '23.11.0'
  AWS_REGION: 'eu-central-1'

jobs:
  # Quality checks job
  quality-checks:
    name: Code Quality & Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

      - name: Run Prettier check (if available)
        run: npm run format
        continue-on-error: true

      - name: Run unit tests
        run: npm run test -- --coverage --watchAll=false --passWithNoTests
        continue-on-error: true

      - name: Run integration tests
        run: npm run test:integration

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: always()
        with:
          files: ./backend/coverage/lcov.info
          fail_ci_if_error: false

  # Build and push Docker image
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: quality-checks
    outputs:
      image-uri: ${{ steps.build.outputs.image-uri }}
      image-tag: ${{ steps.build.outputs.image-tag }}
      registry: ${{ steps.build.outputs.registry }}
      repository: ${{ steps.build.outputs.repository }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_BACKEND_GITHUB_ACTION_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-backend

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate image tag
        id: image-tag
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          IMAGE_TAG="${TIMESTAMP}-${SHORT_SHA}"
          echo "tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: build
        run: |
          REGISTRY="${{ steps.login-ecr.outputs.registry }}"
          REPOSITORY="${{ secrets.BACKEND_ECR_REPOSITORY }}"
          TAG="${{ steps.image-tag.outputs.tag }}"
          
          echo "Registry: ${REGISTRY}"
          echo "Repository: ${REPOSITORY}"
          echo "Tag: ${TAG}"
          
          IMAGE_URI="${REGISTRY}/${REPOSITORY}:${TAG}"
          LATEST_URI="${REGISTRY}/${REPOSITORY}:latest"
          
          echo "Building image with URI: ${IMAGE_URI}"
          
          docker build \
            --target production \
            -t $IMAGE_URI \
            -t $LATEST_URI \
            ./backend
          
          docker push $IMAGE_URI
          docker push $LATEST_URI
          
          # Set outputs using environment variables to avoid secret detection
          echo "image-uri=${IMAGE_URI}" >> $GITHUB_OUTPUT
          echo "image-tag=${TAG}" >> $GITHUB_OUTPUT
          echo "registry=${REGISTRY}" >> $GITHUB_OUTPUT
          echo "repository=${REPOSITORY}" >> $GITHUB_OUTPUT

      - name: Generate deployment artifacts
        run: |
          cat > imagedefinitions.json << EOF
          [
            {
              "name": "${{ secrets.BACKEND_CONTAINER_NAME }}",
              "imageUri": "${{ steps.build.outputs.image-uri }}"
            }
          ]
          EOF

      - name: Upload deployment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deployment-artifacts
          path: imagedefinitions.json
          retention-days: 14

    # Deploy to ECS
  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    needs: [ build-and-push ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download deployment artifacts
        uses: actions/download-artifact@v4
        with:
          name: deployment-artifacts

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_BACKEND_GITHUB_ACTION_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions-backend-deploy

      - name: Deploy to ECS
        run: |
          echo "=== DEBUG: All job outputs ==="
          echo "build-and-push.result: ${{ needs.build-and-push.result }}"
          echo "build-and-push.outputs.image-uri: ${{ needs.build-and-push.outputs.image-uri }}"
          echo "build-and-push.outputs.image-tag: ${{ needs.build-and-push.outputs.image-tag }}"
          echo "build-and-push.outputs.registry: ${{ needs.build-and-push.outputs.registry }}"
          echo "build-and-push.outputs.repository: ${{ needs.build-and-push.outputs.repository }}"
          echo "=========================="
          
          if [ "${{ needs.build-and-push.result }}" != "success" ]; then
            echo "Error: build-and-push job did not succeed (result: ${{ needs.build-and-push.result }})"
            exit 1
          fi
          
          # Try to use direct image-uri output, fallback to reconstructing from components
          IMAGE_URI="${{ needs.build-and-push.outputs.image-uri }}"
          if [ -z "$IMAGE_URI" ]; then
            echo "Image URI output is empty, reconstructing from components..."
            REGISTRY="${{ needs.build-and-push.outputs.registry }}"
            REPOSITORY="${{ needs.build-and-push.outputs.repository }}"
            TAG="${{ needs.build-and-push.outputs.image-tag }}"
            
            if [ -n "$REGISTRY" ] && [ -n "$REPOSITORY" ] && [ -n "$TAG" ]; then
              IMAGE_URI="${REGISTRY}/${REPOSITORY}:${TAG}"
              echo "Reconstructed Image URI: $IMAGE_URI"
            else
              echo "Error: Cannot reconstruct image URI - missing components"
              echo "Registry: $REGISTRY"
              echo "Repository: $REPOSITORY" 
              echo "Tag: $TAG"
              exit 1
            fi
          fi
          
          echo "Using Image URI: $IMAGE_URI"

          TASK_DEFINITION=$(aws ecs describe-services \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --services ${{ secrets.ECS_SERVICE }} \
            --query 'services[0].taskDefinition' \
            --output text)

          aws ecs describe-task-definition \
            --task-definition $TASK_DEFINITION \
            --query 'taskDefinition' > current-task-def.json

          sudo apt-get update && sudo apt-get install -y jq

          jq --arg IMAGE "$IMAGE_URI" \
             '.containerDefinitions[0].image = $IMAGE' \
             current-task-def.json > updated-task-def.json

          jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .placementConstraints, .compatibilities, .registeredAt, .registeredBy)' \
             updated-task-def.json > new-task-def.json

          NEW_TASK_DEF=$(aws ecs register-task-definition \
            --cli-input-json file://new-task-def.json \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)

          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service ${{ secrets.ECS_SERVICE }} \
            --task-definition $NEW_TASK_DEF \
            --force-new-deployment

      - name: Wait for deployment
        run: |
          aws ecs wait services-stable \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --services ${{ secrets.ECS_SERVICE }} \
            --region ${{ env.AWS_REGION }}

      - name: Notify deployment success
        if: success()
        run: |
          echo "🚀 Backend deployment successful!"
          echo "Commit: ${{ github.sha }}"
